### ISSUE TITLE
Fix 1337x

### ISSUE THREAD

**Issue by dausruddin** [boypt/simple-torrent#103]
Search is fine. But when trying to select, it gave an error, 

`No magnet or infohash found`

Thanks.

**Comment by dausruddin** [comment]
Maybe this helps?

https://github.com/anabkhan/cloud-torrent/commit/3bd0fcbbbf09895129a6a66c98edb0878b888df8

**Comment by boypt** [comment]
The search config are actually in https://github.com/boypt/simple-torrent/blob/master/scraper-config.json
exactly the same with mentioned `anabkhan@3bd0fcb`

maybe you search something else? I tried some tv shows and works all right.
I cannot grantee that all this scraper works all the time, because those sites are introducing anti-scraper mechanism.
