### ISSUE TITLE
Search engine - custom scraper-config.json

### ISSUE THREAD

**Issue by TheToto** [boypt/simple-torrent#30]
(feature request)
An option to choose the scraper config file without recompiling

**Comment by msberends** [comment]
Or at least put it in this repo instead of a gist, so we can create pull requests?
I actually wanted to write support for torrenz2.eu, and [looking at the gist](https://gist.github.com/boypt/9bf0e3e876502ae8e521d9ba0487e0e1) I realise that it actually is already there, named "Z2". Super unclear, and it's also broken.

If you put the `scraper-config.json` just into your repo, we can suggest changes.

**Comment by TheToto** [comment]
It's now inside the repo so meh, but i don't use that anymore.
