### ISSUE TITLE
Add support for ffmpeg transcoding videos and stream them while downloading

### ISSUE THREAD

**Issue by bcashier** [boypt/simple-torrent#34]
Hi

Add support for ffmpeg transcoding videos and stream them while downloading.

And if possible using webtorrent support for fast result.

Thanks

**Comment by boypt** [comment]
you can do that by wraping what you need in a simple bash script, like this:

```
#!/bin/bash

if [[ ${CLD_DIR} != "file" ]]; then
  exit 0
fi

VIDEO="${CLD_DIR}/${CLD_PATH}"

ffmpeg -xx -xx -xx -i ${VIDEO} output.xxx.mp4
```

then make sure the script is excutable and configure the path in the `DoneCmd` config of simpletorrent.

**Comment by bcashier** [comment]
There is no built in package on golang?

What about switching time of the video to the last minute for example and torrent not yet fully downloaded?

Thanks again

**Comment by pataquets** [comment]
@bcashier You meant to transcode after finish downloading or while streaming?
If the latter, I think the script won't work, @boypt (unless I'm missing something). I guess we should reopen the issue, then, in case anyone wants to pick up or provide feedback.
To transcode while streaming, I think there's some code which might be useful from [anacrolix/dms](https://github.com/anacrolix/dms), which transcodes on the fly. Specifically in [this file],(https://github.com/anacrolix/dms/blob/master/transcode/transcode.go) if my limited Go-fu is not mistaken.

**Comment by boypt** [comment]
But transcoding needs the data stream to be in the original order, while bittorrent protocol doesn't work this way by default.
I do have an impression that some project achieve this by setting the first data block with higher priority so that the file downloads the the original order, this needs quite a little bit more code.

I found the other project streams torrents in the http stream form: https://github.com/WinPooh32/peerstohttp

maybe it's a better start for your requirement.
