### ISSUE TITLE
Auto update from the UI

### ISSUE THREAD

**Issue by DooML** [boypt/simple-torrent#9]
Update related settings/features would be good such as :

- Automatic updates / OFF or ON
- Update checks interval
- Auto update "only if idle" or "instantly" by pausing the downloading/seeding torrents and resuming after finishing
- Box with info about new features / fixes / changes

It would be a useful feature since it's hard to keep up with the constant updates.

**Comment by boypt** [comment]
There's no easy way to pause the update. The original author design a machanism that by pulling 
 info regularly inside the engine, if a user is connected, will calculate the difference to the last status and push the difference the the webUI. The info include everything, tasks, files, system stats ... pausing the update means all interative lose feedback, unless I rewrite and seprate them in different pushing channels... I woundn't do that! 

About change log I prefer write it in project page/wiki, instead of codes, plus I'm not very familar with the frontend angular framework.

**Comment by DooML** [comment]
Wait so does that mean there's already a built-in updating system?

**Comment by boypt** [comment]
oh.. you mean updating the program itself... theres misunderstand here, i
was talking about internal data updating from engine to web ui.

updating the program itself related to different various OS,  it's
difficult to do it in an easy way. that's why no any other projects using
golang offer a buildin update system.

you can use the quickinstall.sh script to update the program in a modren
linux, while many other users prefer docker, they just update the image.
